### ISSUE TITLE
Feature Request: Specifying valid dates that are not neighboring

### ISSUE THREAD

**Issue by Asheq** [predixdesignsystem/px-calendar-picker#15]
I have a use-case where the user should choose a date from a list of dates that are not neighboring/contiguous. For example: 

    04-10-2018
    04-11-2018
    04-13-2018
    04-17-2018
    04-18-2018
    04-19-2018

As you can see, there are some missing dates: 04-12-2018, 04-14-2018, 04-15-2018, 04-16-2018. 

Would you be able to augment the element to support this use case? The existing `min-date` and `max-date` properties on px-calendar-picker don't suffice, unfortunately. One way might be with a `valid-dates` property that takes an array.

**Comment by benoitjchevalier** [comment]
Maybe you can consider using a dropdown instead if it's just a list of specific dates

**Comment by Asheq** [comment]
That's a nice, simple solution. I'll go that way for now, thanks!
